In [1]:
import numpy as np

# 创建numpy

In [27]:
a = np.array([1, 2, 3])
b = np.array([[1,2,3],[4,5,6]])
a.shape, b.shape

((3,), (2, 3))

In [5]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [6]:
np.ones((1,2))

array([[1., 1.]])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
# 随机整数
np.random.randint(low=2,high=5, size=(2, 4))

array([[3, 2, 2, 3],
       [3, 3, 4, 3]])

In [21]:
# 标准正太分布
np.random.randn(2,4)

array([[ 1.03806847,  1.30595235,  0.06558312,  1.23667291],
       [ 0.7788566 , -0.72952277, -0.93757795,  1.01725608]])

In [25]:
# 0-1之间的随机，两种方法一样不过参数形式不一样，后者接受一个元组
np.random.rand(2,4),np.random.random((2,4))

(array([[0.43472006, 0.00771173, 0.51172634, 0.62719718],
        [0.7879999 , 0.80087178, 0.15814746, 0.68833809]]),
 array([[0.78627737, 0.1602448 , 0.36501283, 0.0379657 ],
        [0.53098944, 0.57668558, 0.86067682, 0.72395911]]))

# 索引切片

In [33]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [36]:
a[0,:],a[1,3]

(array([1, 2, 3, 4]), 8)

In [37]:
# 布尔索引
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12])

# 数据类型

In [43]:
a = np.array([1.1, 1.2],dtype = np.int32)
a.dtype

dtype('int32')

In [44]:
b = a.astype(np.float32)

In [45]:
a.dtype, b.dtype

(dtype('int32'), dtype('float32'))

# 数学计算

In [47]:
# 矩阵计算,直接用*表示的是点乘
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
np.dot(x,y)

(array([[19, 22],
        [43, 50]]),
 array([[ 5, 12],
        [21, 32]]))

In [52]:
# 求和,axis=0表示沿着行累加
x = np.array([[1,2],
              [3,4]])
x.sum(),x.sum(axis=0),x.sum(axis=1),x.T

(10,
 array([4, 6]),
 array([3, 7]),
 array([[1, 3],
        [2, 4]]))

In [54]:
# 最大值，均值
x.max(),x.mean(axis=0)

(4, array([2., 3.]))

In [57]:
# 转换维度
x.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4]])

# np叠加

In [58]:
a=[1,2,3,4]
b=[5,6,7,8]
c=[9,10,11,12]

In [61]:
# 横向叠加
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [64]:
# 纵向叠加
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])